spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql





  mail:
    host: smtp.gmail.com
    port: 587
    username: marta.glinka2002@gmail.com
    password: srdl ljqj gdeb rjik
    properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
    transfer:
      protocol: smtp

app:
  url: http://localhost:5173

