spring:
  datasource:
    url: jdbc:postgresql://controlfood-db.postgres.database.azure.com:5432/postgres
    username: postgres
    password: P@ssword123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql




  flyway: #flyway automatically uses the datasource from the application to connect to the DBs
    enabled: true # enables flyway database migration
    locations: classpath:/migration # the location where flyway should look for migration scripts
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 0.0.0

  #    default-schema: postgresql



  mail:
    host: smtp.gmail.com
    port: 587
    username: marta.glinka2002@gmail.com
    password: srdl ljqj gdeb rjik
    properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
    transfer:
      protocol: smtp

app:
  url: http://localhost:5173


server:
  port: 80


  # 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


